# Generated by Django 5.1.6 on 2025-02-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('le_id', models.AutoField(primary_key=True, serialize=False)),
                ('le_nickname', models.CharField(max_length=50, unique=True)),
                ('le_email', models.EmailField(max_length=254, unique=True)),
                ('le_password', models.CharField(max_length=60)),
                ('le_city', models.CharField(blank=True, max_length=50, null=True)),
                ('le_info', models.TextField(blank=True, null=True)),
                ('le_social_networks', models.TextField(blank=True, null=True)),
                ('le_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sb_id', models.AutoField(primary_key=True, serialize=False)),
                ('sb_name', models.CharField(max_length=100)),
                ('sb_category', models.CharField(choices=[('Programming', 'Programming'), ('Math', 'Math'), ('Languages', 'Languages')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_nickname', models.CharField(max_length=50, unique=True)),
                ('tc_email', models.EmailField(max_length=254, unique=True)),
                ('tc_password', models.CharField(max_length=60)),
                ('tc_city', models.CharField(blank=True, max_length=50, null=True)),
                ('tc_info', models.TextField(blank=True, null=True)),
                ('tc_social_networks', models.TextField(blank=True, null=True)),
                ('tc_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendsByLearner',
            fields=[
                ('fl_id', models.AutoField(primary_key=True, serialize=False)),
                ('fl_learner_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='mainapp.learner')),
                ('fl_learner_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='mainapp.learner')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubject',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('ss_name', models.CharField(max_length=100)),
                ('sb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LearnersSubsubjects',
            fields=[
                ('lss_id', models.AutoField(primary_key=True, serialize=False)),
                ('le_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.learner')),
                ('ss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersSubsubjects',
            fields=[
                ('tss_id', models.AutoField(primary_key=True, serialize=False)),
                ('ss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subsubject')),
                ('tc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
    ]
