# Generated by Django 5.1.6 on 2025-02-25 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмета')),
                ('sb_category', models.CharField(choices=[('Programming', 'Програмування'), ('Math', 'Математика'), ('Languages', 'Мови')], max_length=50, verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('learner', 'Учень'), ('teacher', 'Вчитель'), ('admin', 'Адміністратор')], default='learner', max_length=10)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('social_networks', models.TextField(blank=True, null=True)),
                ('available_times', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_start_date', models.DateField(verbose_name='Дата початку')),
                ('st_end_date', models.DateField(verbose_name='Дата завершення')),
                ('st_format', models.CharField(choices=[('individual', 'Індивідуальне навчання'), ('group', 'Групове навчання')], max_length=50, verbose_name='Формат')),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'learner'}, related_name='study_programs', to=settings.AUTH_USER_MODEL)),
                ('st_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_name', models.CharField(max_length=100, unique=True, verbose_name='Назва підпредмета')),
                ('sb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='LearnersSubsubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersPerStudyPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.studyprogram')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachersSubsubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subsubject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendsByLearner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_time_found', models.DateTimeField(auto_now_add=True, null=True)),
                ('fl_learner_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to=settings.AUTH_USER_MODEL)),
                ('fl_learner_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fl_learner_id_1', 'fl_learner_id_2')},
            },
        ),
        migrations.CreateModel(
            name='LearnersPerTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('learner', 'teacher')},
            },
        ),
    ]
