# Generated by Django 5.1.6 on 2025-02-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsbylearner',
            name='fl_time_found',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='LearnersPerTeachers',
            fields=[
                ('lt_id', models.AutoField(primary_key=True, serialize=False)),
                ('lt_learners_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.learner')),
                ('lt_teachers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_start_date', models.DateField()),
                ('st_end_date', models.DateField()),
                ('st_format', models.CharField(max_length=50)),
                ('st_subject', models.CharField(max_length=50)),
                ('le_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.learner')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersPerStudyPrograms',
            fields=[
                ('tsp_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.studyprogram')),
                ('tc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
    ]
