# Generated by Django 5.1.6 on 2025-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subsubjects',
            field=models.ManyToManyField(blank=True, related_name='users', to='mainapp.subsubject'),
        ),
    ]
