# Generated by Django 5.1.6 on 2025-03-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_subsubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_networks',
        ),
        migrations.AddField(
            model_name='user',
            name='group_teaching',
            field=models.BooleanField(default=False),
        ),
    ]
